spring:
  application:
    name: dubbo-consumer-demo
server:
  port: 8070
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 23456
  registry:
    id: my-reg
    address: zookeeper://localhost:2181